namespace SerwisGitar.Migrations
{
    using System;
    using System.Data.Entity.Migrations;

    public partial class PopulateInstrumentServicesTable : DbMigration
    {
        public override void Up()
        {
            Sql(@"
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (1, 1)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (2, 1)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (3, 1)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (4, 1)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (1, 2)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (3, 2)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (4, 2)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (1, 3)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (3, 3)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (4, 3)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (1, 4)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (3, 4)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (4, 4)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (1, 5)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (3, 5)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (4, 5)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (1, 6)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (2, 6)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (3, 6)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (4, 6)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (1, 7)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (2, 7)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (3, 7)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (4, 7)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (3, 8)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (4, 8)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (2, 9)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (3, 9)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (4, 9)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (3, 10)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (4, 10)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (1, 11)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (3, 11)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (4, 11)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (1, 12)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (2, 12)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (3, 12)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (4, 12)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (3, 13)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (4, 13)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (3, 14)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (4, 14)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (1, 15)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (2, 15)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (3, 15)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (4, 15)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (1, 16)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (2, 16)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (3, 16)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (4, 16)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (1, 17)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (3, 17)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (4, 17)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (1, 18)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (2, 18)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (3, 18)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (4, 18)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (3, 19)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (4, 19)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (3, 20)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (4, 20)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (3, 21)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (4, 21)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (1, 22)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (2, 22)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (3, 22)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (4, 22)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (1, 23)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (3, 23)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (4, 23)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (1, 24)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (2, 24)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (3, 24)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (4, 24)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (1, 25)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (2, 25)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (3, 25)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (4, 25)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (1, 26)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (2, 26)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (3, 26)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (4, 26)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (1, 27)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (2, 27)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (3, 27)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (4, 27)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (1, 28)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (2, 28)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (3, 28)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (4, 28)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (1, 29)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (2, 29)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (3, 29)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (4, 29)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (1, 30)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (2, 30)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (3, 30)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (4, 30)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (1, 31)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (2, 31)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (3, 31)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (4, 31)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (1, 32)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (2, 32)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (3, 32)
                INSERT INTO [dbo].[InstrumentServices] ([InstrumentId], [ServiceId]) VALUES (4, 32)
");
        }

        public override void Down()
        {
        }
    }
}
